{
  "comments": [
    {
      "key": {
        "uuid": "3fa7e38b_6f14454e",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 12898
      },
      "writtenOn": "2019-11-12T01:25:53Z",
      "side": 1,
      "message": "This isn\u0027t mandated right?   A project *may* choose to drop py2 support during U",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 9,
        "endChar": 38
      },
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_b23700b0",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 11904
      },
      "writtenOn": "2019-11-12T02:20:10Z",
      "side": 1,
      "message": "Technically yes, they don\u0027t have to. But any using common libraries like oslo will likely be forced to. I can update the statement to \"Ussuri and later may be Python 3 only\" if you think the commit message will cause confusion.",
      "parentUuid": "3fa7e38b_6f14454e",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 9,
        "endChar": 38
      },
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_d2eddcf0",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 12898
      },
      "writtenOn": "2019-11-12T02:50:02Z",
      "side": 1,
      "message": "Hmmm OK I\u0027m not sure I like the idea of oslo forcing projects to be py3 only, but neither do I like the idea of projects forcing olso to carry py2 code :(\n\nIf we need to respin this review then yes please to updating the commit message but only if we\u0027re re-spinning.",
      "parentUuid": "3fa7e38b_b23700b0",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 9,
        "endChar": 38
      },
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_e6edbaf0",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 260,
      "author": {
        "id": 11904
      },
      "writtenOn": "2019-11-12T12:00:44Z",
      "side": 1,
      "message": "FWIW, this is the allow_3_only\u003dFalse matching case.",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_a6b902ed",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 285,
      "author": {
        "id": 11904
      },
      "writtenOn": "2019-11-12T12:00:44Z",
      "side": 1,
      "message": "And this is the mismatching case. So the unit tests below illustrate the prior test does still succeed, and this unit test will also then succeed by setting the flag.",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_6f3be5e9",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 12898
      },
      "writtenOn": "2019-11-12T01:25:53Z",
      "side": 1,
      "message": "I\u0027m not entirely convinced this test it right.\n\nCertainly I\u0027m having trouble getting it to fail locally.",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_7241880a",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 11904
      },
      "writtenOn": "2019-11-12T02:20:10Z",
      "side": 1,
      "message": "What are you attempting to fail? This should always succeed. It\u0027s a bit redundant with the allow_3_only default, but I felt it was better to have an explicit test to validate that the behavior was no different for those that choose not to remove the py2 entries.",
      "parentUuid": "3fa7e38b_6f3be5e9",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_12e4d40d",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 12898
      },
      "writtenOn": "2019-11-12T02:50:02Z",
      "side": 1,
      "message": "I misunderstood what it was checking.  I was expecting that if I changed ``allow_3_only\u003dTrue`` to False it\u0027d fail (and the other test does.   Then I thought it\u0027d fail if the py2 requirements were different between the project and global_reqs.  But neither of these cause failures.\n\nSo the point is to show that even on branches where py3_only is OK having py2 requirements wont cause requirements-check to fail.  Correct?",
      "parentUuid": "3fa7e38b_7241880a",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3fa7e38b_b2a140ab",
        "filename": "openstack_requirements/tests/test_check.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 11904
      },
      "writtenOn": "2019-11-12T03:01:46Z",
      "side": 1,
      "message": "Correct, this change will allow projects that wish to drop py2 to be able to only track the py3 requirements so as more and more dependencies drop py2, wish is going to start happening a lot, we won\u0027t constantly be breaking everyone\u0027s gate when we add caps that don\u0027t apply to them.",
      "parentUuid": "3fa7e38b_12e4d40d",
      "revId": "ffc55d352a009b178f4ba4bf9c8e36060307d587",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}